# Requirements

## Imports

In [71]:
import pandas as pd
from ipywidgets import interact, interactive
from IPython.display import display
import requests
import bs4 as bs
import bs4
import time
import selenium
from selenium import webdriver
from selenium.webdriver.common.by import By
import matplotlib.pyplot as plt
from ipywidgets import interact, interactive
from IPython.display import display

## Functions

In [2]:
def connect(url):
    page = requests.get(url)
    soup = bs.BeautifulSoup(page.text,"lxml")
    return soup

## Pickle file names

In [3]:
pokemon_stats_df_picklename = 'pokemon_stats_df.pkl'
pokemon_moves_df_picklename = 'pokemon_moves_df.pkl'
pokemon_learnset_df_picklename = 'pokemon_learnset_df.pkl'

# Data Mining

## Pokemon Stats

In [4]:
pokemon_stats_url = 'https://www.serebii.net/pokedex-gs/stat/all.shtml'

soup = connect(pokemon_stats_url)

stats_table_soup = soup.findAll('table',{'class':'dextable'})[0]

ranks = []
poke_index=[]
pokemon = []
main_type =[]
secondary_type =[]
hp=[]
attack=[]
defence = []
special_attack =[]
special_defence =[]
speed = []

for row in stats_table_soup.findAll('tr')[2:]:
    td = row.findAll('td')
    #Rank
    rank = td[0].get_text().split('/')[0].strip()
    if len(rank)>0:
        ranks.append(td[0].get_text().split('/')[0].strip())
    values =  row.findAll('td',{'class':'fooinfo'})
    if len(values)>0:
        #Pokedex Entry
        poke_index.append(values[0].get_text().strip())
        #Pokemon Name
        pokemon.append(values[2].get_text().strip().lower())
        
        #Main ans Secondary type
        types = values[3].findAll('a')

        if len(types)==1:
                main_type.append(types[0].get('href').replace('/pokedex-gs/','').replace('.shtml',''))
                secondary_type.append('None')
        if len(types)==2:
                main_type.append(types[0].get('href').replace('/pokedex-gs/','').replace('.shtml',''))
                secondary_type.append(types[1].get('href').replace('/pokedex-gs/','').replace('.shtml',''))
        
        #Hp
        hp.append(int(values[4].get_text()))
        
        #Attack
        attack.append(int(values[5].get_text()))
        
        #Defence
        defence.append(int(values[6].get_text()))
        
        #Special Attack 
        special_attack.append(int(values[7].get_text()))
        
        #Special Defence
        special_defence.append(int(values[8].get_text()))
        
        #Speed
        speed.append(int(values[9].get_text()))
        

pokemon_stats_df = pd.DataFrame()
pokemon_stats_df['rank']=ranks
pokemon_stats_df['poke_index']=poke_index
pokemon_stats_df['pokemon']=pokemon
pokemon_stats_df['main_type']=main_type
pokemon_stats_df['secondary_type']=secondary_type
pokemon_stats_df['hp']=hp
pokemon_stats_df['attack']=attack
pokemon_stats_df['defence']=defence
pokemon_stats_df['special_attack']=special_attack
pokemon_stats_df['special_defence']=special_defence
pokemon_stats_df['speed']=speed
pokemon_stats_df['total']=pokemon_stats_df['hp']+pokemon_stats_df['attack']+pokemon_stats_df['defence']+pokemon_stats_df['special_attack']+pokemon_stats_df['special_defence']+pokemon_stats_df['speed']


pokemon_stats_df.to_pickle(pokemon_stats_df_picklename)

pokemon_stats_df.head(5)

,rank,poke_index,pokemon,main_type,secondary_type,hp,attack,defence,special_attack,special_defence,speed,total
0,1,#150,mewtwo,psychic,None,106,110,90,154,90,130,680
1,2,#249,lugia,psychic,flying,106,90,130,90,154,110,680
2,3,#250,ho-oh,fire,flying,106,130,90,110,154,90,680
3,4,#149,dragonite,dragon,flying,91,134,95,100,100,80,600
4,5,#151,mew,psychic,None,100,100,100,100,100,100,600

## Pokemon Moves

In [5]:
moves_gen1_url = 'https://pokemondb.net/move/generation/1'
moves_gen2_url = 'https://pokemondb.net/move/generation/2'

soup_gen1 = connect(moves_gen1_url)
soup_gen2 = connect(moves_gen2_url)

gen1_moves_table_soup = soup_gen1.find('table',{'class':'data-table sticky-header block-wide'})
gen2_moves_table_soup = soup_gen2.find('table',{'class':'data-table sticky-header block-wide'})

move_name =[]
move_type =[]
move_category =[]
move_power=[]
move_accuracy =[]
move_pp =[]
move_effect =[]

for row in gen1_moves_table_soup.findAll('tr')[1:]:
    td=row.findAll('td')
    
    #Move Name
    move_name.append(td[0].get_text().lower())
    #Move_Type
    move_type.append(td[1].get_text().lower())
    #Move Category
    move_category.append(td[2].find('img').get('alt'))
    #Move Poer
    move_power.append(int(td[3].get_text().replace('—','0')))
    #Move Accuracy
    move_accuracy.append(td[4].get_text().replace('—','0'))
    #Move PP
    move_pp.append(td[5].get_text().replace('—','0'))
    #Move Effect
    move_effect.append(td[6].get_text())
    
for row in gen2_moves_table_soup.findAll('tr')[1:]:
    td=row.findAll('td')
    
    #Move Name
    move_name.append(td[0].get_text().lower())
    #Move_Type
    move_type.append(td[1].get_text().lower())
    #Move Category
    move_category.append(td[2].find('img').get('alt'))
    #Move Power
    move_power.append(int(td[3].get_text().replace('—','0')))
    #Move Accuracy
    move_accuracy.append(td[4].get_text().replace('—','0'))
    #Move PP
    move_pp.append(td[5].get_text().replace('—','0'))
    #Move Effect
    move_effect.append(td[6].get_text())
    
    
pokemon_moves_df =pd.DataFrame()
pokemon_moves_df['move_name']=move_name
pokemon_moves_df['move_type']=move_type
pokemon_moves_df['move_category']=move_category
pokemon_moves_df['move_power']=move_power
pokemon_moves_df['move_accuracy']=move_accuracy
pokemon_moves_df['move_pp']=move_pp
pokemon_moves_df['move_effect']=move_effect

pokemon_moves_df.to_pickle(pokemon_moves_df_picklename)

pokemon_moves_df.head(5)

,move_name,move_type,move_category,move_power,move_accuracy,move_pp,move_effect
0,absorb,grass,Special,20,100,25,User recovers half the HP inflicted on opponent.
1,acid,poison,Special,40,100,30,May lower opponent's Special Defense.
2,acid armor,poison,Status,0,0,20,Sharply raises user's Defense.
3,agility,psychic,Status,0,0,30,Sharply raises user's Speed.
4,amnesia,psychic,Status,0,0,20,Sharply raises user's Special Defense.

## Pokemon Learnsets

In [6]:
pokemon_learnset_url ='https://pokemondb.net/pokedex/game/gold-silver-crystal'

soup = connect(pokemon_learnset_url)

pokemon_infocards = soup.findAll('div',{'class':'infocard'})

pokemon_learnset_urls =[]

for p in pokemon_infocards:
    pokemon_learnset_urls.append('https://pokemondb.net/'+p.find('a').get('href')+'/moves/2')

pokemon_name =[]
move_name = []
move_power =[]
for pokemon in pokemon_learnset_urls:
#pokemon = pokemon_learnset_urls[0]
    time.sleep(0.5)
    r=requests.get(pokemon)
    pokemon_moves_df_list =[]

    for i in pd.read_html(r.text):
        tables = i['Move'].values
        for t in tables:
            move_name.append(t.lower())
            pokemon_name.append(pokemon.split('/')[5])
        power = i['Power'].values
        for p in power:
            move_power.append(p)
    
pokemon_learnset_df = pd.DataFrame()
pokemon_learnset_df['pokemon']=pokemon_name
pokemon_learnset_df['move_name']=move_name
pokemon_learnset_df['move_power']=move_power


pokemon_learnset_df.drop_duplicates(inplace=True)

pokemon_learnset_df['move_power']=pokemon_learnset_df.move_power.str.replace('—','0').astype(float)

pokemon_learnset_df.to_pickle(pokemon_learnset_df_picklename)

pokemon_learnset_df.head(5)

     pokemon     move_name  move_power
0  chikorita         growl         0.0
1  chikorita        tackle        35.0
2  chikorita    razor leaf        55.0
3  chikorita       reflect         0.0
4  chikorita  poisonpowder         0.0

# Data transformations
## Load the data

In [7]:
pokemon_stats_df= pd.read_pickle(pokemon_stats_df_picklename)
pokemon_moves_df= pd.read_pickle(pokemon_moves_df_picklename).sort_values(by='move_name')
pokemon_learnset_df= pd.read_pickle(pokemon_learnset_df_picklename).sort_values(by='move_name')

## Find non matching moves between datasets

In [8]:
pokemon_moves_df = pokemon_moves_df.loc[pokemon_moves_df['move_name']!='struggle']

not_in_learnset =[]
not_in_moves =[]

print('Values not in pokemon_learnset_df:')
for i in pokemon_moves_df['move_name'].unique():
    if i not in pokemon_learnset_df['move_name'].unique():
        not_in_learnset.append(i)
        print(i)

print('\nValues not in pokemon_moves_df:')
for i in pokemon_learnset_df['move_name'].unique():
    if i not in pokemon_moves_df['move_name'].unique():
        not_in_moves.append(i)
        print(i)


print('\n Mappings list')
mappings = {}
for m,v in zip(not_in_learnset,not_in_moves):
    mappings[m]=v

print(mappings)
pokemon_moves_df.replace(mappings,inplace=True)
pokemon_moves_df.to_pickle(pokemon_moves_df_picklename)

pokemon_moves_df= pd.read_pickle(pokemon_moves_df_picklename)

print('Values not in pokemon_learnset_df:')
for i in pokemon_moves_df['move_name'].unique():
    if i not in pokemon_learnset_df['move_name'].unique():
        not_in_learnset.append(i)
        print(i)

print('\nValues not in pokemon_moves_df:')
for i in pokemon_learnset_df['move_name'].unique():
    if i not in pokemon_moves_df['move_name'].unique():
        not_in_moves.append(i)
        print(i)

Values not in pokemon_learnset_df:
ancient power
bubble beam
double slap
dragon breath
dynamic punch
extreme speed
feint attack
high jump kick
poison powder
sand attack
self-destruct
soft-boiled
solar beam
sonic boom
thunder punch
thunder shock
vise grip

Values not in pokemon_moves_df:
ancientpower
bubblebeam
doubleslap
dragonbreath
dynamicpunch
extremespeed
faint attack
hi jump kick
poisonpowder
sand-attack
selfdestruct
softboiled
solarbeam
sonicboom
thunderpunch
thundershock
vicegrip

 Mappings list
{'ancient power': 'ancientpower', 'bubble beam': 'bubblebeam', 'double slap': 'doubleslap', 'dragon breath': 'dragonbreath', 'dynamic punch': 'dynamicpunch', 'extreme speed': 'extremespeed', 'feint attack': 'faint attack', 'high jump kick': 'hi jump kick', 'poison powder': 'poisonpowder', 'sand attack': 'sand-attack', 'self-destruct': 'selfdestruct', 'soft-boiled': 'softboiled', 'solar beam': 'solarbeam', 'sonic boom': 'sonicboom', 'thunder punch': 'thunderpunch', 'thunder shock': 'thundershock', 'vise grip': 'vicegrip'}
Values not in pokemon_learnset_df:

Values not in pokemon_moves_df:

In [9]:
pokemon_stats_df=pokemon_stats_df.sort_values(by='pokemon')
pokemon_learnset_df =  pokemon_learnset_df.sort_values(by='pokemon')
not_in_learnset =[]
not_in_stats =[]

print('Values not in pokemon_learnset_df:')
for i in pokemon_stats_df['pokemon'].unique():
    if i not in pokemon_learnset_df['pokemon'].unique():
        not_in_learnset.append(i)
        print(i)

print('\nValues not in pokemon_moves_df:')
for i in pokemon_learnset_df['pokemon'].unique():
    if i not in pokemon_stats_df['pokemon'].unique():
        not_in_stats.append(i)
        print(i)
        
print('\n Mappings list')
mappings = {}
for m,v in zip(not_in_learnset,not_in_stats):
    mappings[m]=v

print(mappings)
pokemon_stats_df.replace(mappings,inplace=True)
pokemon_stats_df.to_pickle(pokemon_stats_df_picklename)

pokemon_stats_df= pd.read_pickle(pokemon_stats_df_picklename)

print('Values not in pokemon_learnset_df:')
for i in pokemon_stats_df['pokemon'].unique():
    if i not in pokemon_learnset_df['pokemon'].unique():
        not_in_learnset.append(i)
        print(i)

print('\nValues not in pokemon_moves_df:')
for i in pokemon_learnset_df['pokemon'].unique():
    if i not in pokemon_stats_df['pokemon'].unique():
        not_in_stats.append(i)
        print(i)

Values not in pokemon_learnset_df:
farfetch'd
mr. mime
nidoran♀
nidoran♂

Values not in pokemon_moves_df:
farfetchd
mr-mime
nidoran-f
nidoran-m

 Mappings list
{"farfetch'd": 'farfetchd', 'mr. mime': 'mr-mime', 'nidoran♀': 'nidoran-f', 'nidoran♂': 'nidoran-m'}
Values not in pokemon_learnset_df:

Values not in pokemon_moves_df:

In [11]:
damage = []
move_types =[]
move_categories=[]
for pokemon,move,move_power in zip(pokemon_learnset_df['pokemon'],pokemon_learnset_df['move_name'],pokemon_learnset_df['move_power']):
    pokemon_data = pokemon_stats_df.loc[pokemon_stats_df['pokemon']==pokemon]
    pokemon_attack = pokemon_data['attack'].values[0]
    pokemon_special_attack =pokemon_data['special_attack'].values[0]
    pokemon_types =[pokemon_data['main_type'].values[0],pokemon_data['secondary_type'].values[0]]

    move_type = pokemon_moves_df.loc[pokemon_moves_df['move_name']==move]['move_type'].values[0]
    #move_power = pokemon_moves_df.loc[pokemon_moves_df['move_name']==move]['move_power'].values[0]
    move_category = pokemon_moves_df.loc[pokemon_moves_df['move_name']==move]['move_category'].values[0]

    if move_category =='Physical':
        if move_type in pokemon_types:
            damage.append(((move_power*1.5)*pokemon_attack))
        else:
            damage.append((move_power*pokemon_attack))
    if move_category =='Special':
        if move_type in pokemon_types:
            damage.append(((move_power*1.5)*pokemon_special_attack))
        else:
            damage.append((move_power*pokemon_attack))
    if move_category =='Status':
        damage.append(0)
    move_types.append(move_type)
    move_categories.append(move_category)
    
pokemon_learnset_df['damage']=damage
pokemon_learnset_df['move_type']=move_types
pokemon_learnset_df['move_category']=move_categories

pokemon_learnset_df.to_pickle(pokemon_learnset_df_picklename)

# Interactive Visualizations

## Pokemon Stats

In [85]:
n = 20
pokemon_type = ['all']
pokemon_type.extend(list(pokemon_stats_df['main_type'].sort_values().unique()))

def pokemon_stats_by_type(n,pokemon_type):
    plt.style.use('bmh')
    fig,ax=plt.subplots(2,1,figsize=(16,12))

    pokemon_stats_df= pd.read_pickle(pokemon_stats_df_picklename)

    if pokemon_type =='all':
        top_pokemon_total = pokemon_stats_df.nlargest(columns='total',n=n)[['pokemon','total']]
        ax[0].barh(top_pokemon_total['pokemon'],top_pokemon_total['total'])
        ax[0].invert_yaxis()

        ax[1].hist(pokemon_stats_df['total'],bins=20)
        ax[1].set_xticks([pokemon_stats_df['total'].min()+(25*(i)) for i in range(20)])

    else:
        pokemon_df = pokemon_stats_df.loc[(pokemon_stats_df['main_type']==pokemon_type)|(pokemon_stats_df['secondary_type']==pokemon_type)]
        top_pokemon_total =pokemon_df.nlargest(columns='total',n=n)[['pokemon','total']]
        ax[0].barh(top_pokemon_total['pokemon'],top_pokemon_total['total'])
        ax[0].invert_yaxis()

        ax[1].hist(pokemon_df['total'],bins=20)
        ax[1].set_xticks([pokemon_df['total'].min()+(25*(i)) for i in range(20)])


    plt.show()
    
w = interactive(pokemon_stats_by_type,n=[5,10,15,20,25],pokemon_type=pokemon_type)
display(w)

interactive(children=(Dropdown(description='n', options=(5, 10, 15, 20, 25), value=5), Dropdown(description='p…

In [82]:
list(pokemon_stats_df['main_type'].sort_values().unique())

['bug',
 'dark',
 'dragon',
 'electric',
 'fighting',
 'fire',
 'ghost',
 'grass',
 'ground',
 'ice',
 'normal',
 'poison',
 'psychic',
 'rock',
 'steel',
 'water']

In [445]:
pokemon_stats_df.loc[pokemon_stats_df['pokemon']=='ursaring']

,rank,poke_index,pokemon,main_type,secondary_type,hp,attack,defence,special_attack,special_defence,speed,total
52,53,#217,ursaring,normal,None,90,130,75,75,75,55,500

In [446]:
(130*1.5)*120

23400.0

In [7]:
moves['Power']= moves['Power'].str.replace('—','0')

NameError: name 'moves' is not defined

In [8]:
moves['Power']=moves['Power'].astype('int')

NameError: name 'moves' is not defined

In [9]:
moves.nlargest(columns='Power',n=30)

NameError: name 'moves' is not defined

In [10]:
r = requests.get('https://bulbapedia.bulbagarden.net/wiki/List_of_Pok%C3%A9mon_by_index_number_(Generation_II)')
pokemons = pd.read_html(r.text)[0]

pokemons

ValueError: No tables found

In [11]:
df

1,Rank,Nat No.,Pic,Name,Type,HP,Att,Def,S.Atk,S.Def,Spd,Total Base Stat
2,1 / 251,#150,NaN,Mewtwo,NaN,106,110,90,154,90,130,680
3,2 / 251,#249,NaN,Lugia,NaN,106,90,130,90,154,110,680
4,3 / 251,#250,NaN,Ho-Oh,NaN,106,130,90,110,154,90,680
5,4 / 251,#149,NaN,Dragonite,NaN,91,134,95,100,100,80,600
6,5 / 251,#151,NaN,Mew,NaN,100,100,100,100,100,100,600
...,...,...,...,...,...,...,...,...,...,...,...,...
248,247 / 251,#172,NaN,Pichu,NaN,20,40,15,35,35,60,205
249,248 / 251,#129,NaN,Magikarp,NaN,20,10,55,15,20,80,200
250,249 / 251,#010,NaN,Caterpie,NaN,45,30,35,20,20,45,195
251,250 / 251,#013,NaN,Weedle,NaN,40,35,30,20,20,50,195
252,251 / 251,#191,NaN,Sunkern,NaN,30,30,30,30,30,30,180

In [1]:
nums = set([1,1,2,3,3,3,5,5])
print(len(nums))

4

In [5]:
df = pd.read_pickle('Pokemon_BaseStats_GenI-II.pkl')

In [10]:
len(df.iloc[0])

12

In [11]:
x={5,4}
y={1,2,4,5}
x<y

True

In [ ]:
SELECT skill_id,COUNT(question_id)
from question_skills
Group by skill_id
ORDER by COUNT(question_id) DESC